// Editorial destinations for names that differ from the book's section titles.
// These are teaching passages, not glossary hits. Specific technical questions
// still go through equation aliases and ranked source retrieval.
export const navigationTopics = [
  ["philosophy-heading-4d246aa74f", ["self supervised learning", "self supervision", "learning without labels"]],
  ["philosophy-heading-2bc1526f2c", ["LeCun agent", "autonomous machine intelligence", "proposed agent"]],
  ["philosophy-heading-5aa838a105", ["state observation memory", "partial observability"]],
  ["philosophy-heading-871bd47150", ["predicting representations", "representation prediction"]],
  ["philosophy-heading-7a166ba692", ["energy based models", "energy based model", "energy function"]],
  ["philosophy-heading-e65830e76c", ["hierarchical planning", "planning hierarchy"]],
  ["jepa-diagram-0cb7a9bd34", ["JEPA architecture", "joint embedding predictive architecture", "JEPA block diagram"]],
  ["jepa-heading-19d6e602db", ["representation collapse", "collapse", "collapsed encoder"]],
  ["jepa-heading-064b1b50b3", ["contrastive learning", "contrastive loss", "InfoNCE"]],
  ["jepa-heading-947b9a95b1", ["teacher branch", "EMA teacher", "stop gradient"]],
  ["jepa-heading-342a4cc748", ["VICReg", "VICReg loss"]],
  ["probability-paragraph-3698e73877", ["Bayes theorem", "Bayes rule", "Bayesian update"]],
  ["probability-heading-34d7000edb", ["normal distribution", "Gaussian distribution"]],
  ["clouds-heading-8c446fbebd", ["multivariate Gaussian", "multivariate normal distribution"]],
  ["clouds-heading-df2a56c8b8", ["whitening", "whitening transform"]],
  ["calculus-heading-3045db7243", ["chain rule"]],
  ["testing-heading-f7e66a2d29", ["normality tests", "normality test", "Gaussianity test", "hypothesis testing"]],
  ["testing-heading-da422a8575", ["null hypothesis", "null distribution", "null model"]],
  ["testing-heading-64671cf285", ["Kolmogorov Smirnov", "KS test"]],
  ["testing-heading-cdb2fb90e1", ["p value", "p values", "pvalue", "pvalues", "Monte Carlo calibration"]],
  ["testing-heading-3b1cd22173", ["test versus penalty", "test versus regularizer"]],
  ["sigreg-heading-e4d34786a0", ["characteristic function", "distributional fingerprint"]],
  ["sigreg-heading-7fe760e073", ["Gaussian characteristic function", "Gaussian fingerprint"]],
  ["sigreg-heading-8d23ea3ed3", ["empirical characteristic function"]],
  ["sigreg-heading-2e068201e2", ["Cramer Wold", "Cramer Wold theorem", "Cramer Wold principle", "random projections"]],
  ["sigreg-heading-d75f3a1054", ["SIGReg loss", "SIGReg objective", "SIGReg quadrature", "SIGReg integral"]],
  ["planning-heading-60312f2cf4", ["planning", "model based planning"]],
  ["planning-heading-b35d95e647", ["CEM", "cross entropy method"]],
  ["planning-heading-dd365b790a", ["MPC", "model predictive control", "receding horizon"]],
];
